# Name of this configuration
name: "chick"

# The project identifier:
project: "PXD009861"

# The repository (optional):
repo: "PRIDE"

# The glob pattern used to fine the MGF files:
mgf_pattern: "*293T*.mgf"

# The name of the spectral library:
library: "massive_human_hcd_unique_targetdecoy.splib"

# The pattern to download the library.
# Note this is different from library because it is a gzipped tar archive.
library_pattern: "massive*"

# Use a GPU?
gpu: False

# The ANN-SoLo config file:
search_conf: "ann_solo-chick.ini"

# Download previous results for comparison?
compare: True
