# Name of this configuration
name: "iPRG2012"

# The project identifier:
project: "PXD009861"

# The repository (optional):
repo: "PRIDE"

# The glob pattern used to fine the MGF files:
mgf_pattern: "iPRG2012.mgf"

# The name of the spectral library:
library: "human_yeast_targetdecoy.splib"

# The pattern to download the library.
# Note this is different from library because it is a gzipped tar archive.
library_pattern: "human_yeast*"

# Use a GPU?
gpu: False

# The ANN-SoLo config file:
search_conf: "ann_solo-iprg.ini"

# Download previous results for comparison?
compare: False
